#!/bin/bash
curl "https://raw.githubusercontent.com/sinolnil/myenv/main/tmux"      >/$HOME/.tmux.conf
curl "https://raw.githubusercontent.com/sinolnil/myenv/main/vim"     >/$HOME/.vimrc
curl "https://raw.githubusercontent.com/sinolnil/myenv/main/gitconfig" >/$HOME/.gitconfig
